### PR TITLE
Migrate from admission v1beta1 to admission v1 and remove vendoring

### PR DESCRIPTION
**Pull request by rikatz**
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@gmail.com>

AS k8s v1.22, Admission Registration has dropped version v1beta1 and kept only v1 (available since k8s v1.16).

This PR migrates the libraries to use admission Registration v1, and also removes the old vendoring system, focusing directly on go mod (default for go 1.16)

### CODE REVIEW

**Comment by electrocucaracha** [comment]
Fixes #30

**Comment by invidian** [comment]
@vsliouniaev could you have a look into this PR?

**Comment by jonkerj** [comment]
To state the obvious: without this PR, certgen will not run on latest Kubernetes. This complicates the installation of kube-prometheus-stack, for example.

**Comment by vsliouniaev** [comment]
I no longer have access rights to this repository and it is no longer being maintained by the company. There is already a fork of this in the [ingress-nginx repo](https://github.com/kubernetes/ingress-nginx/tree/main/images/kube-webhook-certgen), which has updated APIs and is hosted on GCR: https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml#L569

**Comment by invidian** [comment]
Thanks for the reply @vsliouniaev. It seems `ingress-nginx/kube-webhook-certgen:v1.0` is a good replacement.

Perhaps this repository should be archived then...

**Pull request closed without merging**
